<a href="https://colab.research.google.com/github/maithstartup/Practical-Machine-Learning-Bootcamp/blob/master/numpy_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy **Data Types**

In [0]:
import numpy as np
import pandas as pd

In [0]:
arr=np.array([0,1,2])

In [3]:
arr

array([0, 1, 2])

**Attributes of array**







1.   ndim
2.   shape

1.   size
2.   dtype

1.   itemsize
2.   data














In [4]:
arr.ndim

1

In [5]:
arr.shape

(3,)

In [6]:
arr.size

3

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.itemsize

8

In [9]:
arr.data

In [12]:
datatypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

Playing with Datatypes

In [0]:
arr_1=np.array([0,1,2],dtype=np.float32)

In [14]:
arr_1.dtype

dtype('float32')

In [0]:
arr_2=np.array([0,1,0,1,1],dtype=np.bool_)

In [16]:
print(arr_2)
print(arr_2.dtype)

[False  True False  True  True]
bool


In [17]:
arr_3 = np.array([3+2j, 3-7j], dtype=np.complex64)
arr_3.dtype

dtype('complex64')

In [18]:
arr_4=np.array(["he","welcome","to","ml","course"])
print(arr_4.dtype)
print(arr_4)

<U7
['he' 'welcome' 'to' 'ml' 'course']


In [19]:
arr_4=np.array(["he","welcome","to","ml","course"],dtype=np.string_)
print(arr_4.dtype)
print(arr_4)

|S7
[b'he' b'welcome' b'to' b'ml' b'course']


Conversion

astype

In [20]:
arr_5 = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr_5.dtype))

arr_5 = arr_5.astype(np.float32)
print('Data Type After Conversion: ' + str(arr_5.dtype))
print(arr_5)

Original Data Type: int16
Data Type After Conversion: float32
[1. 2. 3.]


In [22]:
arr_6 = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr_6.dtype))

arr_6 = arr_6.astype(np.bool_)
print('Data Type After Conversion: ' + str(arr_6.dtype))
print(arr_6)

Original Data Type: int16
Data Type After Conversion: bool
[ True  True  True]


In [23]:
arr_7 = np.array([126,130,258], dtype='int16')
print('Original Data Type: ' + str(arr_7.dtype))

# Range of int8 [-128, 127], 258 overflows after conversion

arr_7 = arr_7.astype(np.int8)
print('Data Type After Conversion: ' + str(arr_7.dtype))
print(arr_7)

Original Data Type: int16
Data Type After Conversion: int8
[ 126 -126    2]


[Data Types](https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes)

[Byteorder](https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html)

In [0]:
datatypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)